### ISSUE TITLE
Extending with incoming callers number

### ISSUE THREAD

**Issue by royduin** [devgeeks/PhoneListener#1]
Hi,

I'm a programmer (php and js) but can't write java code. Just a request if you would like to extend it to get the incoming callers number to.
I've found this stackoverflow question with a code example how to do it: http://stackoverflow.com/questions/1853220/retrieve-incoming-calls-phone-number-in-android

I hope you would help me with this.

Thanks!

**Comment by devgeeks** [comment]
Once upon a time, someone else asked me to do this and I did it on a branch for them.

Sadly, when the main plugin got updated for "modern" cordova, the branch didn't get updated.

Then when I split the plugin off into its own repo that branch didn't follow.

I have attempted to merge that branch into a new "extended" branch on this version of the plugin.

Hopefully it will actually work ;)

https://github.com/devgeeks/PhoneListener/tree/extended

**Comment by royduin** [comment]
Thanks you very much! I'll dig into it.
