### ISSUE TITLE
Class not found

### ISSUE THREAD

**Issue by royduin** [devgeeks/PhoneListener#2]
Hi,

I'm trying to get it working with Phonegap (Build) but I keep getting the "class not found" error. Can you make a small example zip file which I can upload on Phonegap Build that works? That will help me a lot!

I'm looking forward to your response! Thanks!

**Comment by devgeeks** [comment]
Hi... the problem is probably that you cannot use just any plugin with the PhoneGap Build service. They have a list of plugins that will work with their service (the Facebook one, a barcode scanner, etc), but this plugin isn't on that list, sorry.

**Comment by royduin** [comment]
Thanks for your reply! But referring here: https://build.phonegap.com/docs/plugins on the bottom of the page they say It is possible with a plugin.xml file. I've tried a lot with it, but I keep tetting the "class not found" error. Maybe you can push me in the right direction?

**Comment by devgeeks** [comment]
Yeah, but for now you can still only use the plugins in their curated list. PhoneListener hasn't been submitted or even updated to use a plugin.xml and conform to the new plugin spec.

"Right now, you cannot submit your own plugins to PhoneGap Build and have them included on our system. We are working on the infrastructure changes to allow this support."

**Comment by royduin** [comment]
Sadly. I hoop they will integrate it soon! For now, I'll just wait.

**Comment by devgeeks** [comment]
I wouldn't hold your breath.

What are you using PhoneListener for?

**Comment by royduin** [comment]
Haha, right. 

I'm working on a Android app (low priority) which catches all the incoming phone calls and the number. Then It has to send the incoming call number to the server and look If the number is present in the database. In case it is, the respective name is returned and has to be displayed on the screen.

The thoughts about this is that when I don't have the number of the incoming call in my address book on my phone I've got a second opinion in the database which is connected to all the people listened in the phone book in my country. So I see who is calling.

It's not unique, see: https://play.google.com/store/apps/details?id=com.webascender.callerid&hl=nl but the apps already on the market doesn't recognize numbers from my country.
