### ISSUE TITLE
The type Plugin is deprecated

### ISSUE THREAD

**Issue by chathudan** [devgeeks/PhoneListener#3]
Hi 

i m using phongap 2.6.0 , PhoneListner gives "The type Plugin is deprecated" and "The method getContext() is undefined for the type CordovaInterface"

**Comment by devgeeks** [comment]
Yeah, it hasn't been updated for 2.6.0

There is a new plugin someone made that is up to date and does basically the something:

https://github.com/madeinstefano/PhoneStateChangeListener

You could try that?

**Comment by chathudan** [comment]
Thank you Tommy
